pub use loyal_hub_abi::{
    CONFIG_MAGIC, CONFIG_SEED, HUB_AUTHORITY_SEED, INITIALIZE_CONFIG, MAX_ALLOWED_MINTS,
    MAX_REBALANCE_TRANSFERS, REBALANCE_INVENTORY, SET_ADMIN, SET_HUB_AUTHORIZER,
    SET_INVENTORY_REBALANCER, SET_LANE_COUNT, SET_MAX_FEE, SET_PAUSED, SWAP_EXACT_IN,
    WITHDRAW_INVENTORY,
};

pub const HUB_CONFIG_SPACE: usize = loyal_hub_abi::CONFIG_ACCOUNT_MAX_LEN;
pub const ASSOCIATED_TOKEN_PROGRAM_ID: pinocchio::pubkey::Pubkey =
    pinocchio_pubkey::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL");
pub const SYSTEM_PROGRAM_ID: pinocchio::pubkey::Pubkey =
    pinocchio_pubkey::pubkey!("11111111111111111111111111111111");
