package backyard

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/solana-foundation/solana-go/v2"
	"github.com/solana-foundation/solana-go/v2/rpc"

	"github.com/loyal-labs/loyal-yield-routing/go/workers/internal/chain"
)

const (
	voltrWithdrawalReceiptDataLength = 112
	voltrWithdrawalReceiptPrefix     = 106
	maxConfirmedObservationAttempts  = 3
)

var (
	// Generated by @voltr/vault-sdk's requestWithdrawVaultReceipt account.
	voltrWithdrawalReceiptDiscriminator = [8]byte{203, 81, 223, 141, 175, 108, 101, 114}
	voltrReceiptPDASeed                 = []byte("request_withdraw_vault_receipt")
	voltrPDAFinalMarker                 = []byte("ProgramDerivedAddress")
)

type VoltrWithdrawalReceipt struct {
	Address                          string
	Vault, User                      string
	AmountLPEscrowed                 uint64
	AmountAssetToWithdrawDecimalBits *big.Int
	UpperBoundAssetRaw               uint64
	WithdrawableFromTS               uint64
	Bump, Version                    uint8
}

type programAccount struct {
	Address string
	Account ConfirmedAccount
}

func getVoltrWithdrawalReceiptAccounts(ctx context.Context, c *chain.Client, voltrProgram, vault string, minContextSlot int64) (int64, []programAccount, error) {
	if minContextSlot <= 0 {
		return 0, nil, fmt.Errorf("positive minimum context slot is required")
	}
	keys, err := publicKeys([]string{voltrProgram, vault})
	if err != nil {
		return 0, nil, err
	}
	slot, read, err := c.ProgramAccounts(ctx, keys[0], []rpc.RPCFilter{
		{Memcmp: &rpc.RPCFilterMemcmp{Offset: 0, Bytes: voltrWithdrawalReceiptDiscriminator[:]}},
		{Memcmp: &rpc.RPCFilterMemcmp{Offset: 8, Bytes: keys[1][:]}},
	}, rpc.CommitmentConfirmed, uint64(minContextSlot))
	if err != nil {
		return 0, nil, confirmedObservationUnavailable(err)
	}
	seen := make(map[solana.PublicKey]struct{}, len(read))
	accounts := make([]programAccount, 0, len(read))
	for _, account := range read {
		if _, duplicate := seen[account.Key]; duplicate {
			return 0, nil, fmt.Errorf("duplicate receipt account %s", account.Key)
		}
		seen[account.Key] = struct{}{}
		address := account.Key.String()
		accounts = append(accounts, programAccount{Address: address, Account: confirmedAccount(address, &account)})
	}
	return int64(slot), accounts, nil
}

// DecodeVoltrWithdrawalReceipt decodes the deployed 112-byte account, not the
// SDK's 106-byte prefix alone. Its program owner, vault, PDA, bump/version,
// amounts, and six trailing zero bytes are all validated before use.
func DecodeVoltrWithdrawalReceipt(account ConfirmedAccount, address, voltrProgram, vault string, vaultCapRaw uint64) (VoltrWithdrawalReceipt, error) {
	if account.Address != "" && account.Address != address {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt address envelope mismatch")
	}
	if account.Owner != voltrProgram || account.Lamports == 0 || account.Executable || len(account.Data) != voltrWithdrawalReceiptDataLength {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt account envelope mismatch")
	}
	if !bytes.Equal(account.Data[:8], voltrWithdrawalReceiptDiscriminator[:]) || !allZero(account.Data[voltrWithdrawalReceiptPrefix:]) {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt layout mismatch")
	}
	vaultKey, err := decodeBase58PublicKey(vault)
	if err != nil {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("invalid configured vault: %w", err)
	}
	if !bytes.Equal(account.Data[8:40], vaultKey[:]) {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt vault mismatch")
	}
	user := encodeBase58(account.Data[40:72])
	amountLP := binary.LittleEndian.Uint64(account.Data[72:80])
	amountBits := new(big.Int).SetBytes(reverseCopy(account.Data[80:96]))
	deadline := binary.LittleEndian.Uint64(account.Data[96:104])
	bump, version := account.Data[104], account.Data[105]
	if amountLP == 0 || amountBits.Sign() <= 0 || deadline == 0 || version != 0 {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt has invalid amount, deadline, or version")
	}
	upperBound, err := ceilU80F48(amountBits)
	if err != nil || upperBound > vaultCapRaw {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt amount exceeds approved cap")
	}
	expected, expectedBump, err := deriveVoltrWithdrawalReceiptPDA(voltrProgram, vault, user)
	if err != nil {
		return VoltrWithdrawalReceipt{}, err
	}
	if address != expected || bump != expectedBump {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt is not the canonical vault/user PDA")
	}
	return VoltrWithdrawalReceipt{Address: address, Vault: vault, User: user, AmountLPEscrowed: amountLP, AmountAssetToWithdrawDecimalBits: amountBits, UpperBoundAssetRaw: upperBound, WithdrawableFromTS: deadline, Bump: bump, Version: version}, nil
}

func ceilU80F48(decimalBits *big.Int) (uint64, error) {
	if decimalBits == nil || decimalBits.Sign() <= 0 {
		return 0, fmt.Errorf("non-positive fixed-point amount")
	}
	plus := new(big.Int).Add(decimalBits, new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 48), big.NewInt(1)))
	plus.Rsh(plus, 48)
	if !plus.IsUint64() {
		return 0, fmt.Errorf("fixed-point amount overflows u64")
	}
	return plus.Uint64(), nil
}

func reverseCopy(value []byte) []byte {
	result := make([]byte, len(value))
	for i := range value {
		result[len(value)-1-i] = value[i]
	}
	return result
}

// Solana PDAs are SHA-256 seeded public keys that must be off the Edwards25519
// curve. This small implementation keeps the observer independent from a full
// Solana client and only supports this fixed receipt seed shape.
func deriveVoltrWithdrawalReceiptPDA(program, vault, user string) (string, uint8, error) {
	programKey, err := decodeBase58PublicKey(program)
	if err != nil {
		return "", 0, err
	}
	vaultKey, err := decodeBase58PublicKey(vault)
	if err != nil {
		return "", 0, err
	}
	userKey, err := decodeBase58PublicKey(user)
	if err != nil {
		return "", 0, err
	}
	for bump := 255; bump >= 0; bump-- {
		hash := sha256.New()
		_, _ = hash.Write(voltrReceiptPDASeed)
		_, _ = hash.Write(vaultKey[:])
		_, _ = hash.Write(userKey[:])
		_, _ = hash.Write([]byte{byte(bump)})
		_, _ = hash.Write(programKey[:])
		_, _ = hash.Write(voltrPDAFinalMarker)
		candidate := hash.Sum(nil)
		if !ed25519CompressedPointOnCurve(candidate) {
			return encodeBase58(candidate), uint8(bump), nil
		}
	}
	return "", 0, fmt.Errorf("no off-curve PDA bump")
}

func ed25519CompressedPointOnCurve(encoded []byte) bool {
	if len(encoded) != 32 {
		return false
	}
	// y is the lower 255 bits of the compressed encoding.
	yBytes := append([]byte(nil), encoded...)
	yBytes[31] &= 0x7f
	p := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 255), big.NewInt(19))
	y := new(big.Int).SetBytes(reverseCopy(yBytes))
	if y.Cmp(p) >= 0 {
		return false
	}
	y2 := new(big.Int).Mul(y, y)
	y2.Mod(y2, p)
	numerator := new(big.Int).Sub(y2, big.NewInt(1))
	numerator.Mod(numerator, p)
	d := new(big.Int).Sub(p, big.NewInt(121665))
	d.Mul(d, new(big.Int).ModInverse(big.NewInt(121666), p))
	d.Mod(d, p)
	denominator := new(big.Int).Mul(d, y2)
	denominator.Add(denominator, big.NewInt(1))
	denominator.Mod(denominator, p)
	inverse := new(big.Int).ModInverse(denominator, p)
	if inverse == nil {
		return false
	}
	x2 := numerator.Mul(numerator, inverse)
	x2.Mod(x2, p)
	// p == 5 mod 8: sqrt exists iff x^((p-1)/2) is one.
	legendreExponent := new(big.Int).Sub(p, big.NewInt(1))
	legendreExponent.Rsh(legendreExponent, 1)
	return new(big.Int).Exp(x2, legendreExponent, p).Cmp(big.NewInt(1)) == 0 || x2.Sign() == 0
}

func decodeBase58PublicKey(input string) ([32]byte, error) {
	var result [32]byte
	decoded, err := decodeKey(input)
	if err != nil || encodeBase58(decoded[:]) != input {
		return result, fmt.Errorf("non-canonical base58 public key")
	}
	copy(result[:], decoded[:])
	return result, nil
}
