package backyardrwa

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"testing"
)

// Cross-client protocol vector generated by the current production compiler.
// Artificial blockhash and zero signature; never a live report or authorization.
func TestExportClientReportMessage(t *testing.T) {
	path := os.Getenv("CLIENT_REPORT_VECTOR")
	if path == "" {
		t.Skip("explicit output path required")
	}
	request := BridgeBuildRequest{Action: ReportNAV, Report: BridgeReport{Sequence: 447487692, ObservedSlot: 447487692, NAVAfterRaw: 1234567, SnapshotDigest: sha256Bytes([]byte("controlled-client-report"))}, AdaptorConfig: bridgeStrategy, Settings: bridgeSettings, RecentBlockhash: bridgeVault, LastValidBlockHeight: 99}
	message, err := CompileBridgeMessage(request)
	if err != nil {
		t.Fatal(err)
	}
	wire := append(make([]byte, 65), message...)
	wire[0] = 1
	data, err := json.MarshalIndent(map[string]any{"schema": "client-report-compiler-vector/v1", "proofLevel": "UNSIGNED_COMPILER_VECTOR_NOT_CONSUMED_REPORT", "request": request, "wireBase64": base64.StdEncoding.EncodeToString(wire), "messageSHA256": sha256Bytes(message)}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = f.Write(data); err != nil {
		f.Close()
		t.Fatal(err)
	}
	if err = f.Close(); err != nil {
		t.Fatal(err)
	}
}
