package backyardrwa

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math/big"
	"sort"
)

const (
	voltrWithdrawalReceiptDataLength = 112
	voltrWithdrawalReceiptPrefix     = 106
	maxConfirmedObservationAttempts  = 3
)

var (
	// Generated by @voltr/vault-sdk's requestWithdrawVaultReceipt account.
	voltrWithdrawalReceiptDiscriminator = [8]byte{203, 81, 223, 141, 175, 108, 101, 114}
	voltrReceiptPDASeed                 = []byte("request_withdraw_vault_receipt")
	voltrPDAFinalMarker                 = []byte("ProgramDerivedAddress")
)

// TokenCustodySpec pins a plain SPL/Token-2022 custody. No identity is learned
// from RPC; each is supplied by the route configuration before it is read.
type TokenCustodySpec struct {
	Address, TokenProgram, Mint, Authority string
}

// VoltrObservationConfig contains the full immutable identity set used by the
// read-only observation. IdleCustody is part of Custodies and is the one whose
// amount is used to calculate an immediate withdrawal shortfall.
type VoltrObservationConfig struct {
	VoltrProgram, Vault string
	IdleCustody         string
	Custodies           []TokenCustodySpec
	IdleFloorRaw        uint64
	VaultCapRaw         uint64
}

func (c VoltrObservationConfig) validate() error {
	if _, err := decodeBase58PublicKey(c.VoltrProgram); err != nil {
		return fmt.Errorf("invalid Voltr program: %w", err)
	}
	if _, err := decodeBase58PublicKey(c.Vault); err != nil {
		return fmt.Errorf("invalid Voltr vault: %w", err)
	}
	if c.IdleCustody == "" || len(c.Custodies) == 0 || c.IdleFloorRaw > c.VaultCapRaw {
		return fmt.Errorf("incomplete Voltr observation configuration")
	}
	seen := make(map[string]struct{}, len(c.Custodies))
	idlePresent := false
	for _, custody := range c.Custodies {
		if custody.Address == "" || custody.TokenProgram == "" || custody.Mint == "" || custody.Authority == "" {
			return fmt.Errorf("incomplete custody identity")
		}
		if _, duplicate := seen[custody.Address]; duplicate {
			return fmt.Errorf("duplicate custody address")
		}
		seen[custody.Address] = struct{}{}
		if custody.Address == c.IdleCustody {
			idlePresent = true
		}
		if _, err := decodeBase58PublicKey(custody.Address); err != nil {
			return fmt.Errorf("invalid custody address: %w", err)
		}
		if _, err := decodeBase58PublicKey(custody.Mint); err != nil {
			return fmt.Errorf("invalid custody mint: %w", err)
		}
		if _, err := decodeBase58PublicKey(custody.Authority); err != nil {
			return fmt.Errorf("invalid custody authority: %w", err)
		}
		if custody.TokenProgram != classicTokenProgram && custody.TokenProgram != token2022Program {
			return fmt.Errorf("unsupported custody token program")
		}
	}
	if !idlePresent {
		return fmt.Errorf("idle custody is not pinned")
	}
	return nil
}

type VoltrWithdrawalReceipt struct {
	Address                          string
	Vault, User                      string
	AmountLPEscrowed                 uint64
	AmountAssetToWithdrawDecimalBits *big.Int
	UpperBoundAssetRaw               uint64
	WithdrawableFromTS               uint64
	Bump, Version                    uint8
}

type VoltrWithdrawalDemand struct {
	Slot                        int64
	Receipts                    []VoltrWithdrawalReceipt
	Custodies                   []ConfirmedAccount
	ConfirmedIdleRaw            uint64
	PendingWithdrawalUpperBound uint64
	RequiredIdleRaw             uint64
	IdleShortfallRaw            uint64
}

type programAccount struct {
	Address string
	Account ConfirmedAccount
}

// ScanVoltrWithdrawalDemand is intentionally signer-free. It retries only
// read calls until the receipt namespace and every pinned custody account come
// from one confirmed context slot; it never fabricates a mixed-slot snapshot.
func (c *RPCClient) ScanVoltrWithdrawalDemand(ctx context.Context, config VoltrObservationConfig) (VoltrWithdrawalDemand, error) {
	if err := config.validate(); err != nil {
		return VoltrWithdrawalDemand{}, err
	}
	addresses := make([]string, len(config.Custodies))
	byAddress := make(map[string]TokenCustodySpec, len(config.Custodies))
	for index, spec := range config.Custodies {
		addresses[index] = spec.Address
		byAddress[spec.Address] = spec
	}
	minSlot, err := c.ConfirmedSlot(ctx)
	if err != nil {
		return VoltrWithdrawalDemand{}, err
	}
	for attempt := 0; attempt < maxConfirmedObservationAttempts; attempt++ {
		receiptSlot, rawReceipts, err := c.getVoltrWithdrawalReceiptAccounts(ctx, config.VoltrProgram, config.Vault, minSlot)
		if err != nil {
			return VoltrWithdrawalDemand{}, err
		}
		custodySlot, custodies, err := c.GetMultipleAccounts(ctx, addresses, minSlot)
		if err != nil {
			return VoltrWithdrawalDemand{}, err
		}
		if receiptSlot != custodySlot {
			if receiptSlot > custodySlot {
				minSlot = receiptSlot
			} else {
				minSlot = custodySlot
			}
			continue
		}
		receipts := make([]VoltrWithdrawalReceipt, 0, len(rawReceipts))
		for _, raw := range rawReceipts {
			receipt, err := DecodeVoltrWithdrawalReceipt(raw.Account, raw.Address, config.VoltrProgram, config.Vault, config.VaultCapRaw)
			if err != nil {
				return VoltrWithdrawalDemand{}, err
			}
			receipts = append(receipts, receipt)
		}
		sort.Slice(receipts, func(i, j int) bool { return receipts[i].Address < receipts[j].Address })
		idleRaw := uint64(0)
		for _, account := range custodies {
			spec, exists := byAddress[account.Address]
			if !exists {
				return VoltrWithdrawalDemand{}, fmt.Errorf("unexpected custody account %s", account.Address)
			}
			if account.Executable || account.Lamports == 0 {
				return VoltrWithdrawalDemand{}, fmt.Errorf("custody account envelope mismatch: %s", account.Address)
			}
			mint, _ := decodeBase58PublicKey(spec.Mint)
			authority, _ := decodeBase58PublicKey(spec.Authority)
			decoded, err := DecodeTokenCustody(account.Owner, account.Data, mint, authority)
			if err != nil {
				return VoltrWithdrawalDemand{}, fmt.Errorf("decode custody %s: %w", account.Address, err)
			}
			if account.Address == config.IdleCustody {
				idleRaw = decoded.Raw
			}
		}
		pending, err := sumReceiptUpperBounds(receipts)
		if err != nil {
			return VoltrWithdrawalDemand{}, err
		}
		if pending > config.VaultCapRaw-config.IdleFloorRaw {
			return VoltrWithdrawalDemand{}, fmt.Errorf("withdrawal demand exceeds vault cap")
		}
		required := config.IdleFloorRaw + pending
		shortfall := uint64(0)
		if required > idleRaw {
			shortfall = required - idleRaw
		}
		return VoltrWithdrawalDemand{
			Slot: receiptSlot, Receipts: receipts, Custodies: custodies, ConfirmedIdleRaw: idleRaw,
			PendingWithdrawalUpperBound: pending, RequiredIdleRaw: required, IdleShortfallRaw: shortfall,
		}, nil
	}
	return VoltrWithdrawalDemand{}, fmt.Errorf("confirmed receipt and custody reads did not align after %d attempts", maxConfirmedObservationAttempts)
}

func sumReceiptUpperBounds(receipts []VoltrWithdrawalReceipt) (uint64, error) {
	var total uint64
	for _, receipt := range receipts {
		if ^uint64(0)-total < receipt.UpperBoundAssetRaw {
			return 0, fmt.Errorf("withdrawal demand overflow")
		}
		total += receipt.UpperBoundAssetRaw
	}
	return total, nil
}

func (c *RPCClient) getVoltrWithdrawalReceiptAccounts(ctx context.Context, voltrProgram, vault string, minContextSlot int64) (int64, []programAccount, error) {
	if minContextSlot <= 0 {
		return 0, nil, fmt.Errorf("positive minimum context slot is required")
	}
	var result struct {
		Context struct {
			Slot int64 `json:"slot"`
		} `json:"context"`
		Value []struct {
			Pubkey  string `json:"pubkey"`
			Account struct {
				Owner      string          `json:"owner"`
				Lamports   uint64          `json:"lamports"`
				Data       json.RawMessage `json:"data"`
				Executable bool            `json:"executable"`
			} `json:"account"`
		} `json:"value"`
	}
	discriminator58 := encodeBase58(voltrWithdrawalReceiptDiscriminator[:])
	err := c.call(ctx, "getProgramAccounts", []any{voltrProgram, map[string]any{
		"commitment": "confirmed", "encoding": "base64", "withContext": true, "minContextSlot": minContextSlot,
		"filters": []any{
			map[string]any{"memcmp": map[string]any{"offset": 0, "bytes": discriminator58}},
			map[string]any{"memcmp": map[string]any{"offset": 8, "bytes": vault}},
		},
	}}, &result)
	if err != nil {
		return 0, nil, confirmedObservationUnavailable(err)
	}
	if result.Context.Slot < minContextSlot {
		return 0, nil, confirmedObservationUnavailable(fmt.Errorf("incoherent confirmed receipt response"))
	}
	seen := make(map[string]struct{}, len(result.Value))
	accounts := make([]programAccount, 0, len(result.Value))
	for _, value := range result.Value {
		if _, err := decodeBase58PublicKey(value.Pubkey); err != nil {
			return 0, nil, fmt.Errorf("invalid receipt address: %w", err)
		}
		if _, duplicate := seen[value.Pubkey]; duplicate {
			return 0, nil, fmt.Errorf("duplicate receipt account %s", value.Pubkey)
		}
		seen[value.Pubkey] = struct{}{}
		data, err := decodeRPCBase64(value.Account.Data, value.Pubkey)
		if err != nil {
			return 0, nil, err
		}
		accounts = append(accounts, programAccount{Address: value.Pubkey, Account: ConfirmedAccount{
			Address: value.Pubkey, Owner: value.Account.Owner, Lamports: value.Account.Lamports, Data: data, Executable: value.Account.Executable,
		}})
	}
	return result.Context.Slot, accounts, nil
}

func decodeRPCBase64(raw json.RawMessage, address string) ([]byte, error) {
	var encoded []string
	if err := json.Unmarshal(raw, &encoded); err != nil || len(encoded) != 2 || encoded[1] != "base64" {
		return nil, fmt.Errorf("account %s has invalid base64 encoding", address)
	}
	data, err := base64.StdEncoding.DecodeString(encoded[0])
	if err != nil {
		return nil, fmt.Errorf("decode account %s: %w", address, err)
	}
	return data, nil
}

// DecodeVoltrWithdrawalReceipt decodes the deployed 112-byte account, not the
// SDK's 106-byte prefix alone. Its program owner, vault, PDA, bump/version,
// amounts, and six trailing zero bytes are all validated before use.
func DecodeVoltrWithdrawalReceipt(account ConfirmedAccount, address, voltrProgram, vault string, vaultCapRaw uint64) (VoltrWithdrawalReceipt, error) {
	if account.Address != "" && account.Address != address {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt address envelope mismatch")
	}
	if account.Owner != voltrProgram || account.Lamports == 0 || account.Executable || len(account.Data) != voltrWithdrawalReceiptDataLength {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt account envelope mismatch")
	}
	if !bytes.Equal(account.Data[:8], voltrWithdrawalReceiptDiscriminator[:]) || !allZero(account.Data[voltrWithdrawalReceiptPrefix:]) {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt layout mismatch")
	}
	vaultKey, err := decodeBase58PublicKey(vault)
	if err != nil {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("invalid configured vault: %w", err)
	}
	if !bytes.Equal(account.Data[8:40], vaultKey[:]) {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt vault mismatch")
	}
	user := encodeBase58(account.Data[40:72])
	amountLP := binary.LittleEndian.Uint64(account.Data[72:80])
	amountBits := new(big.Int).SetBytes(reverseCopy(account.Data[80:96]))
	deadline := binary.LittleEndian.Uint64(account.Data[96:104])
	bump, version := account.Data[104], account.Data[105]
	if amountLP == 0 || amountBits.Sign() <= 0 || deadline == 0 || version != 0 {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt has invalid amount, deadline, or version")
	}
	upperBound, err := ceilU80F48(amountBits)
	if err != nil || upperBound > vaultCapRaw {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt amount exceeds approved cap")
	}
	expected, expectedBump, err := deriveVoltrWithdrawalReceiptPDA(voltrProgram, vault, user)
	if err != nil {
		return VoltrWithdrawalReceipt{}, err
	}
	if address != expected || bump != expectedBump {
		return VoltrWithdrawalReceipt{}, fmt.Errorf("receipt is not the canonical vault/user PDA")
	}
	return VoltrWithdrawalReceipt{Address: address, Vault: vault, User: user, AmountLPEscrowed: amountLP, AmountAssetToWithdrawDecimalBits: amountBits, UpperBoundAssetRaw: upperBound, WithdrawableFromTS: deadline, Bump: bump, Version: version}, nil
}

func ceilU80F48(decimalBits *big.Int) (uint64, error) {
	if decimalBits == nil || decimalBits.Sign() <= 0 {
		return 0, fmt.Errorf("non-positive fixed-point amount")
	}
	plus := new(big.Int).Add(decimalBits, new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 48), big.NewInt(1)))
	plus.Rsh(plus, 48)
	if !plus.IsUint64() {
		return 0, fmt.Errorf("fixed-point amount overflows u64")
	}
	return plus.Uint64(), nil
}

func reverseCopy(value []byte) []byte {
	result := make([]byte, len(value))
	for i := range value {
		result[len(value)-1-i] = value[i]
	}
	return result
}

// Solana PDAs are SHA-256 seeded public keys that must be off the Edwards25519
// curve. This small implementation keeps the observer independent from a full
// Solana client and only supports this fixed receipt seed shape.
func deriveVoltrWithdrawalReceiptPDA(program, vault, user string) (string, uint8, error) {
	programKey, err := decodeBase58PublicKey(program)
	if err != nil {
		return "", 0, err
	}
	vaultKey, err := decodeBase58PublicKey(vault)
	if err != nil {
		return "", 0, err
	}
	userKey, err := decodeBase58PublicKey(user)
	if err != nil {
		return "", 0, err
	}
	for bump := 255; bump >= 0; bump-- {
		hash := sha256.New()
		_, _ = hash.Write(voltrReceiptPDASeed)
		_, _ = hash.Write(vaultKey[:])
		_, _ = hash.Write(userKey[:])
		_, _ = hash.Write([]byte{byte(bump)})
		_, _ = hash.Write(programKey[:])
		_, _ = hash.Write(voltrPDAFinalMarker)
		candidate := hash.Sum(nil)
		if !ed25519CompressedPointOnCurve(candidate) {
			return encodeBase58(candidate), uint8(bump), nil
		}
	}
	return "", 0, fmt.Errorf("no off-curve PDA bump")
}

func ed25519CompressedPointOnCurve(encoded []byte) bool {
	if len(encoded) != 32 {
		return false
	}
	// y is the lower 255 bits of the compressed encoding.
	yBytes := append([]byte(nil), encoded...)
	yBytes[31] &= 0x7f
	p := new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 255), big.NewInt(19))
	y := new(big.Int).SetBytes(reverseCopy(yBytes))
	if y.Cmp(p) >= 0 {
		return false
	}
	y2 := new(big.Int).Mul(y, y)
	y2.Mod(y2, p)
	numerator := new(big.Int).Sub(y2, big.NewInt(1))
	numerator.Mod(numerator, p)
	d := new(big.Int).Sub(p, big.NewInt(121665))
	d.Mul(d, new(big.Int).ModInverse(big.NewInt(121666), p))
	d.Mod(d, p)
	denominator := new(big.Int).Mul(d, y2)
	denominator.Add(denominator, big.NewInt(1))
	denominator.Mod(denominator, p)
	inverse := new(big.Int).ModInverse(denominator, p)
	if inverse == nil {
		return false
	}
	x2 := numerator.Mul(numerator, inverse)
	x2.Mod(x2, p)
	// p == 5 mod 8: sqrt exists iff x^((p-1)/2) is one.
	legendreExponent := new(big.Int).Sub(p, big.NewInt(1))
	legendreExponent.Rsh(legendreExponent, 1)
	return new(big.Int).Exp(x2, legendreExponent, p).Cmp(big.NewInt(1)) == 0 || x2.Sign() == 0
}

func decodeBase58PublicKey(input string) ([32]byte, error) {
	var result [32]byte
	decoded, err := decodeKey(input)
	if err != nil || encodeBase58(decoded[:]) != input {
		return result, fmt.Errorf("non-canonical base58 public key")
	}
	copy(result[:], decoded[:])
	return result, nil
}
